[panel]
position = "bottom"
height = 30

[[widgets]]
type = "menu"
text = "Menu"
align = "left"

[[widgets]]
type = "tray"
align = "left"

[[widgets]]
type = "cmdbtn"
align = "right"
command = "csvol"
text = "Volume"

[[widgets]]
type = "clock"
align = "right"
format = "%H:%M:%S"
